version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  contractservice:
    container_name: contractservice
    image: contractservice:latest
    depends_on:
      - "goodsservice"
    build:
      context: contractservice
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
  
  goodsservice:
    container_name: goodsservice
    image: goodsservice:latest
    build:
      context: goodsservice
      dockerfile: Dockerfile    
    networks:
      - services-network